### ISSUE TITLE
Tracking issue: CI refactoring

### ISSUE THREAD

**Issue by xopham** [sse-secure-systems/connaisseur#914]
## Description
Initial refactoring step https://github.com/sse-secure-systems/connaisseur/pull/622 resolved several topics already. Some remaining tasks are tracked in this issue.

Major changes:
- new build system
  - implement GHCR to store images as packages in pipeline
  - use buildkit for image build -> SBOMs, Provenance
  - sign packages using cosign
- modular CI ([reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) and actions)
- refactor CI

Improvements:
- integrated with GitHub Security
- modular CI
- faster builds
- signed builds
- nightly builds
- provenance and SBOMs added
- broader code scanning coverage

TBD:
- [ ] summary update
- [ ] rm trivy-released-image-scan into sca job
- [ ] join docs into main workflows
- [ ] update "required tests"
- [ ] matrix strategy for `dockerhub-check`

Open Question:
- OK to add registry to helm chart? seems more explicit and less reliant on a random default
- OK to rename "nightly-scans" to "nightly"?
- can we drop tag engineering?
- should we make everything reusable with selector for which jobs to drop?
- now only relying on Github security not pipeline fail
- IMPORANT: mitigate risk of overwriting tags!

Missing (create issues for remaining):
- [ ] release workflow + test
- [x] somehow `getRoot` fails on nightly
- [ ] update public getRoot image
- [ ] rework all actions
- [ ] consider caching for build and integration tests
- [ ] speedup by reduction of integration tests
- [x] remove `update` upload
- [x] consider usage of https://github.com/marketplace/actions/docker-metadata-action
- [ ] use GH action specific parsing: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
- [ ] add verify tag functionality for cosign validation to connaisseur
- [ ] sign scans
- [ ] add semgrep
- [x] add checkov
- [ ] automated local testing with remote builds
- [ ] confirm dependabot update actions by commitSHA (checkout actions are purposely outdated by two minor versions)
- [ ] finetune [checkov](https://github.com/marketplace/actions/checkov-github-action)
- [ ] resolve OSSF Scorecard findings
- [ ] publish OSSF Scorecard findings
- [ ] merge upgrade int test into bash script
- [ ] why has cosign [output changed](https://github.com/sse-secure-systems/connaisseur/actions/runs/4258789437/jobs/7410395811)? 
- [ ] harmonize usage of `yq` (see https://github.com/sse-secure-systems/connaisseur/pull/622#discussion_r1109874661)
- [ ] consider dropping `Uninstall` when not necessary (see https://github.com/sse-secure-systems/connaisseur/pull/622#discussion_r1116865206)
- [ ] switch back to strict github security evaluation
- [ ] don't run integration tests on push to develop
- [ ] external MRs are not allowed to initiate push to packages? good? bad?
